" vundle 环境设置
filetype off 
set rtp+=~/.vim/bundle/Vundle.vim
" vundle 管理的插件列表必须位于 vundle#begin() 和 vundle#end() 之间
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'Lokaltog/vim-powerline'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'sickill/vim-monokai'
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
" 插件列表结束
call vundle#end()
 
syntax enable
"syntax on
let g:syntastic_check_on_open = 0

"colorscheme solarized
" 设置状态栏主题风格
"let g:Powerline_colorscheme='solarized256'
set background=dark
colorscheme monokai

" 总是显示状态栏
set laststatus=2
" 显示光标当前位置
set ruler
" 开启行号显示
set number                                                                                                                                                    
" 高亮显示当前行/列
set cursorline
"set cursorcolumn
"highlight CursorLine   cterm=NONE ctermbg=reverse ctermfg=None guibg=NONE guifg=NONE
"highlight CursorColumn cterm=NONE ctermbg=grey ctermfg=None guibg=NONE guifg=NONE

" 高亮显示搜索结果
set hlsearch

" 自适应不同语言的智能缩进
filetype indent on
" 将制表符扩展为空格
set expandtab
" 设置编辑时制表符占用空格数
set tabstop=4
" 设置格式化时制表符占用空格数
set shiftwidth=4
" 让 vim 把连续数量的空格视为一个制表符
set softtabstop=4
 
" 基于缩进或语法进行代码折叠
" za，打开或关闭当前折叠；zM，关闭所有折叠；zR，打开所有折叠
"set foldmethod=indent
set foldmethod=syntax
" 启动 vim 时关闭折叠代码
set nofoldenable

let g:ycm_server_python_interpreter='/usr/bin/python'
let g:ycm_global_ycm_extra_conf='~/.vim/.ycm_extra_conf.py'
let g:ycm_show_diagnostics_ui = 0
" 补全功能在注释中同样有效
let g:ycm_complete_in_comments=1
" 从第一个键入字符就开始罗列匹配项
let g:ycm_min_num_of_chars_for_completion=1
" 禁止缓存匹配项，每次都重新生成匹配项
" let g:ycm_cache_omnifunc=0
" 开启 YCM 标签补全引擎
let g:ycm_collect_identifiers_from_tags_files=1
" 语法关键字补全            
let g:ycm_seed_identifiers_with_syntax=1
inoremap <leader>; <C-x><C-o>

map <F10> :NERDTreeToggle<CR>
let g:NERDTreeWinPos = "right"

